### ISSUE TITLE
Included example that uses fern doesn't log anything

### ISSUE THREAD

**Issue by alcroito** [vorner/log-reroute#1]
The example at https://docs.rs/log-reroute/0.1.6/log_reroute/ doesn't send any output to the terminal.

It's missing a `log::set_max_level(LevelFilter::Info);` statement (or another level).

When fern is used without log-reroute, it usually calls `set_max_level` in https://docs.rs/fern/0.6.0/fern/struct.Dispatch.html#method.apply

The example does not call `apply` though and thus all log calls end up discarded.

log-reroute version: `0.1.6`
fern version: `0.6.0`

P.S.
Thank you for the useful crate!

**Comment by vorner** [comment]
Thank you for noticing. Yes, you're right, `LevelFilter::Off` doesn't turn off that filter, but logging O:-).
